ebase := EMSCTTFixtureTest EMSCTTGridConvergence
LibNames := BoxTools
include $(CHOMBO_HOME)/mk/Make.test
CPPFLAGS += -I../../Examples/EMS \
    -I../../Source/utils -I../../Source/simd \
    -I../../Source/CCZ4 -I../../Source/Matter \
    -I../../Source/Cartoon -I../../Source/BoxUtils \
    -I../../Source/GRChomboCore \
    -I../../Source/InitialConditions/EMSBH \
    -I../../Source/InitialConditions/EMSBH/1D_SOL
